spring.application.name=mygoReaction
server.port=12345
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = pg1
spring.datasource.password = password1234
spring.jpa.hibernate.ddl-auto = update